version: '3.8'

services:

  couchdb:
    image: couchdb:3.3
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
